/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface FHEPrivateWalletInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "confidentialProtocolId"
      | "deposit"
      | "getEncryptedBalance"
      | "getMyEncryptedBalance"
      | "privatePay"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "Deposited" | "PrivatePaymentPlanned"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "confidentialProtocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "deposit",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getEncryptedBalance",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getMyEncryptedBalance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "privatePay",
    values: [AddressLike, BytesLike, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "confidentialProtocolId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getEncryptedBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMyEncryptedBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "privatePay", data: BytesLike): Result;
}

export namespace DepositedEvent {
  export type InputTuple = [user: AddressLike, newEncryptedBalance: BytesLike];
  export type OutputTuple = [user: string, newEncryptedBalance: string];
  export interface OutputObject {
    user: string;
    newEncryptedBalance: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PrivatePaymentPlannedEvent {
  export type InputTuple = [
    user: AddressLike,
    to: AddressLike,
    encryptedAmount: BytesLike
  ];
  export type OutputTuple = [user: string, to: string, encryptedAmount: string];
  export interface OutputObject {
    user: string;
    to: string;
    encryptedAmount: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface FHEPrivateWallet extends BaseContract {
  connect(runner?: ContractRunner | null): FHEPrivateWallet;
  waitForDeployment(): Promise<this>;

  interface: FHEPrivateWalletInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  confidentialProtocolId: TypedContractMethod<[], [bigint], "view">;

  deposit: TypedContractMethod<
    [encryptedAmount: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  getEncryptedBalance: TypedContractMethod<
    [user: AddressLike],
    [string],
    "view"
  >;

  getMyEncryptedBalance: TypedContractMethod<[], [string], "view">;

  privatePay: TypedContractMethod<
    [to: AddressLike, encryptedAmount: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "confidentialProtocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "deposit"
  ): TypedContractMethod<
    [encryptedAmount: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getEncryptedBalance"
  ): TypedContractMethod<[user: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "getMyEncryptedBalance"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "privatePay"
  ): TypedContractMethod<
    [to: AddressLike, encryptedAmount: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "Deposited"
  ): TypedContractEvent<
    DepositedEvent.InputTuple,
    DepositedEvent.OutputTuple,
    DepositedEvent.OutputObject
  >;
  getEvent(
    key: "PrivatePaymentPlanned"
  ): TypedContractEvent<
    PrivatePaymentPlannedEvent.InputTuple,
    PrivatePaymentPlannedEvent.OutputTuple,
    PrivatePaymentPlannedEvent.OutputObject
  >;

  filters: {
    "Deposited(address,bytes32)": TypedContractEvent<
      DepositedEvent.InputTuple,
      DepositedEvent.OutputTuple,
      DepositedEvent.OutputObject
    >;
    Deposited: TypedContractEvent<
      DepositedEvent.InputTuple,
      DepositedEvent.OutputTuple,
      DepositedEvent.OutputObject
    >;

    "PrivatePaymentPlanned(address,address,bytes32)": TypedContractEvent<
      PrivatePaymentPlannedEvent.InputTuple,
      PrivatePaymentPlannedEvent.OutputTuple,
      PrivatePaymentPlannedEvent.OutputObject
    >;
    PrivatePaymentPlanned: TypedContractEvent<
      PrivatePaymentPlannedEvent.InputTuple,
      PrivatePaymentPlannedEvent.OutputTuple,
      PrivatePaymentPlannedEvent.OutputObject
    >;
  };
}
